name       : os-installer
version    : 14.0
release    : 80
source     :
    - https://github.com/solus-project/os-installer/archive/v14.tar.gz : 05839f9f61752858ed17ae2b71bb43de72662dfb7cce8dcf4aeabeec80f6b348
homepage   : https://www.solus-project.com
license    :
    - GPL-2.0
summary    : Install OS to disk
builddeps  :
    - python-setuptools
rundeps    :
    - gsettings-desktop-schemas
    - libgnome-desktop
    - libtimezonemap
    - gparted
    - python-cairo
    - python-geoip
    - python-gobject
    - python-parted
    - setxkbmap
description: |
    Install OS to disk
build      : |
    python setup.py build
install    : |
    python setup.py install --root="$installdir"

    # Assets
    install -D -m 00644 dist/org.freedesktop.policykit.pkexec.policy $installdir/usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    install -D -m 00755 dist/os-installer-wrapper $installdir/usr/bin/os-installer-wrapper
    install -D -m 00644 $pkgfiles/10-livecd.rules $installdir/usr/share/polkit-1/rules.d/10-livecd.rules
    install -D -m 00644 dist/install-symbolic.svg $installdir/usr/share/icons/gnome/scalable/actions/install-symbolic.svg

    # Temporary! AppSystem borkage
    install -D -m 00644 dist/com.solus_project.Installer.desktop $installdir/usr/share/applications/os-installer-gtk.desktop
