name       : os-installer
version    : 5.4.1
release    : 41
source     :
    - https://github.com/solus-project/os-installer/archive/v5.4.1.tar.gz : 6c1b2276b4e8f1c47d6457ff75d9cd5e74f7ba3eaca852df037e999785430abc
homepage   : https://www.solus-project.com
license    :
    - GPL-2.0
summary    : Install OS to disk
builddeps  :
    - python-setuptools
rundeps    :
    - setxkbmap
    - libtimezonemap
    - gparted
    - python-parted
    - python-geoip
    - python-cairo
    - python-gobject
description: |
    Install OS to disk
setup      : |
    %patch -p1 < $pkgfiles/0001-Take-off-the-safety-switch.-Can-t-be-held-accountabl.patch
    %patch -p1 < $pkgfiles/0002-Add-the-missing-install-symbolic.patch
    %patch -p1 < $pkgfiles/0003-Preserve-the-.disk-member.patch
    %patch -p1 < $pkgfiles/0004-Incorporate-missing-SVGs.patch
    %patch -p1 < $pkgfiles/0005-Undo-borks-so-we-can-fail-gracefully.patch
build      : |
    python setup.py build
install    : |
    python setup.py install --root="$installdir"

    # Assets
    install -D -m 00644 dist/com.solus_project.Installer.desktop $installdir/usr/share/applications/com.solus_project.Installer.Desktop
    install -D -m 00644 dist/org.freedesktop.policykit.pkexec.policy $installdir/usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    install -D -m 00755 dist/os-installer-wrapper $installdir/usr/bin/os-installer-wrapper
    install -D -m 00644 $pkgfiles/10-livecd.rules $installdir/etc/polkit-1/rules.d/10-livecd.rules
    install -D -m 00644 dist/install-symbolic.svg $installdir/usr/share/icons/gnome/scalable/actions/install-symbolic.svg
